Copy from master.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,56 +1,94 @@
-#!/bin/sh
+#!/bin/bash
 
 # script/bootstrap: Resolve all dependencies that the application requires to
-#                   run.
+# run.
 
-set -e
+#set -e
 
 echo "Installing required dependencies for Anaconda";
 
-
 #######################################
-#- Variable Setup
+#- Source Variable Setup
 #######################################
-THE_GID="1066";
-THE_GROUP="conda";
-THE_APP="conda";
-PYTHON_VERSION="3.9";
+export THE_CONFIG_DIR="/workspaces/jbooks/script";
+export THE_CONFIG="${THE_CONFIG_DIR}/config.env";
 
-#this is because this file is synced to my dotfiles repo and will be symbolically linked later
-THE_RC="/workspaces/.codespaces/.persistedshare/dotfiles/.bashrc";
-CONDA_EXE=$(which conda)
-CONDA_DIR="/opt/conda";
-CONDA_ENV_NAME="machine_learning";
+echo "...establishing variables.";
+if ! [ -f "${THE_CONFIG}" ];
+then
+    echo "...attempted to source ${SOURCE_FILE} and could not find it.  Without this file there's no point in attempting to continue.";
+    exit 1
+fi
 
-sudo groupadd -r "${THE_GROUP}" --gid ${THE_GID} || echo "...failed to add group ${THE_GROUP}, perhaps it already exists.";
+source "${THE_CONFIG}";
+
+if [ -f "${CONDA_EXE}" ];
+then
+    echo "...confirmed Anaconda executable is at least present, continue build.";
+else
+    echo "...unable to locate ${CONDA_EXE}, cannot create an Anaconda env without this executable.";
+    echo "Perhaps Anaconda isn't installed.";
+    echo "CHECK YOUR devcontainer / Dockerfile configuration.";
+    #exit gracefully so the dotfiles carry into the build at least.
+    exit 0
+fi
+
+echo "...adding group for conda.";
+echo "...testing for group named conda.";
+IS_CONDA_GROUP=$(getent group conda | wc -l);
+if [ "${IS_CONDA_GROUP}" -eq 0 ];
+then
+    sudo groupadd -r "${THE_GROUP}" --gid ${THE_GID} || echo "...failed to add group ${THE_GROUP}, perhaps it already exists.";
+fi
 
 THE_VERIFIED_GID=$(getent group conda | awk -F: '{printf "%d", $3}')
 echo "...verified ${THE_GROUP}'s Group Id is: ${THE_VERIFIED_GID}";
 
-if ! [ -f /etc/profile.d/conda.sh ];
+echo "...testing for symbolic link of conda environment to ${CONDA_LINK}";
+if ! [ -f "${CONDA_LINK}" ] && ! [ -h "${CONDA_LINK}" ];
 then
-	sudo ln -s ${CONDA_DIR}/etc/profile.d/conda.sh /etc/profile.d/conda.sh  || echo "...failed to link conda.sh to /etc/profile.d";
+    if [ -f ${CONDA_DIR}${CONDA_LINK} ];
+    then
+        sudo ln -s "${CONDA_DIR}${CONDA_LINK}" "${CONDA_LINK}"  || echo "...failed to link conda.sh to /etc/profile.d";
+    else
+        echo "...${CONDA_DIR}${CONDA_LINK} does not exist, nothing to symbolically link...you might have a problem.";
+    fi
 else
-	echo ".../etc/profile.d/conda.sh already symbolically linked";
+    echo "...${CONDA_LINK} already symbolically linked";
 fi
 
+echo "...testing for sourcing of conda.sh in your ${THE_RC}";
 IS_SOURCED=$(grep "conda.sh" "${THE_RC}" | wc -l);
 if [ "${IS_SOURCED}" -eq 0 ];
 then
-	sudo echo ". /usr/local/${THE_APP}/etc/profile.d/conda.sh" >> "${THE_RC}" || echo "...failed to include source reference of conda.sh in .bashrc";
+    if [ -f "${THE_RC}" ];
+    then
+        sudo echo ". /usr/local/${THE_APP}/etc/profile.d/conda.sh" >> "${THE_RC}" || echo "...failed to include source reference of conda.sh in ${THE_RC}";
+    else
+        echo "...unable to locate the ${THE_RC}, you might have a bigger problem as in Anaconda is not installed.";
+	echo "......adding source reference to ~/.bashrc";
+        sudo echo ". /usr/local/${THE_APP}/etc/profile.d/conda.sh" >> ~/.bashrc || echo "...failed to include source reference of conda.sh in .bashrc";
+    fi
 else
-	echo "...${THE_RC} already setup for sourcing conda.";
-	echo "......this will later be symbolically linked to ~/.bashrc";
+    echo "...${THE_RC} already setup for sourcing conda.";
+    echo "......this will later be symbolically linked to ~/.bashrc";
 fi
 
+echo "...testing for conda activation in your ${THE_RC}";
 IS_ACTIVATED=$(grep "conda activate base" "${THE_RC}" | wc -l)
 if [ "${IS_ACTIVATED}" -eq 0 ];
 then
-	sudo echo "${THE_APP} activate base" >> "${THE_RC}"  || echo "...failed to include call to conda activate in .bashrc";
+    if [ -f "${THE_RC}" ];
+    then
+        sudo echo "${THE_APP} activate base" >> "${THE_RC}"  || echo "...failed to include call to conda activate in .bashrc";
+    else
+        echo "...unable to locate the ${THE_RC}, you might have a bigger problem as in Anaconda is not installed.";
+    fi
 else
-	echo "...${THE_RC} already setup for conda activation.";
-	echo "......this will later be symbolically linked to ~/.bashrc";
+    echo "...${THE_RC} already setup for conda activation.";
+    echo "......this will later be symbolically linked to ~/.bashrc";
 fi
+
 
 THE_USERNAME="vscode";
 sudo /usr/sbin/usermod -aG "${THE_GROUP}" "${THE_USERNAME}"  || echo "...failed to usermod -aG ${THE_GROUP} ${THE_USERNAME}"
@@ -58,4 +96,44 @@ sudo /usr/sbin/usermod -aG "${THE_GROUP}" "${THE_USERNAME}"  || echo "...failed 
 #######################################
 #- Install required Anaconda Packages
 #######################################
-sudo ${CONDA_EXE} env create --file /workspaces/jbooks/environment/archless_environment.yml
+if [ -f "${CONDA_EXE}" ];
+then
+    if [ -f "${CONDA_EXE}" ];
+    then
+        sudo ${CONDA_EXE} env create --file "${THE_ANACONDA_ENV}"
+    else
+        echo "...unable to locate ${THE_ANACONDA_ENV}, your repo has an issue.";
+    fi
+else
+    echo "...unable to locate ${CONDA_EXE}, cannot create an Anaconda env without this executable.  Perhaps Anaconda isn't installed.";
+fi
+
+
+#######################################
+#- Install required folders and data associated with this effort
+#######################################
+for the_dir in ${THE_DIRS[@]}
+do
+    echo "...creating ${the_dir}"
+    mkdir -p "/workspaces/${the_dir}" || echo "......failed to create /workspaces/${the_dir}, expect the notebook to fail.";
+    ${CHMOD_EXE} -R u+rwx "/workspaces/${the_dir}";
+done
+
+#######################################
+#- Download the data file and place it for the user
+#######################################
+export ORIGINAL_DIR=$(pwd);
+cd "${THE_ROOT}";
+confirm=$( ${WGET_EXE} --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id='$GOOGLE_FILE_ID -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
+${WGET_EXE} --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$confirm&id=$GOOGLE_FILE_ID" -O ${THE_DATA} && rm -rf /tmp/cookies.txt
+
+if [ -f "${THE_DATA}" ];
+then
+    ${TAR_EXE} xvfz "${THE_DATA}";
+    ${RM_EXE} -rf "${THE_DATA}";
+    ${CHMOD_EXE} -R u+rwx "${THE_ROOT}/data";
+else
+    echo "...unable to locate ${THE_DATA}.  Perhaps the download didn't work.  Without ${THE_ROOT}/data your notebook won't work.";
+fi
+
+cd "${ORIGINAL_DIR}";
